### ISSUE TITLE
mybatisPlus问题

### ISSUE THREAD

**Issue by tdoor** [PerccyKing/batslog#10]
我知道这个不是为mb适配的 但是普通使用没什么问题的,在mp的.last()函数启动后SQL参数就会变成问号
wrapper.eq("kjnd", data.getStr("NF"))
                .eq("kjqj", data.getStr("YF"))
                .notInSql("code", "select isnull(vouchercode,'') from VoucherSummary")
                .orderByDesc("code")
                .last("offset 50*" + pageNum + " rows fetch next 50 rows only;");
去掉  .last()就正常
如果后续打算适配的话

**Comment by PerccyKing** [comment]
能否提供一下console打印的日志呢，插件的原理是解析控制台日志来实现的

**Comment by tdoor** [comment]
2021-05-12 11:30:34.051  INFO 13504 --- [nio-9700-exec-6] com.zaxxer.hikari.HikariDataSource       : SpringBootDemoHikariCP - Starting...
2021-05-12 11:30:34.577  INFO 13504 --- [nio-9700-exec-6] com.zaxxer.hikari.HikariDataSource       : SpringBootDemoHikariCP - Start completed.
2021-05-12 11:30:34.582 DEBUG 13504 --- [nio-9700-exec-6] c.u.k.m.VoucherMapper.sqlBuilderInt      : ==>  Preparing: select count(*) from uto_view_kb_020 where code not in (select isnull(vouchercode,'') from VoucherSummary) and kjnd = 2020 and kjqj = 01 
2021-05-12 11:30:34.598 DEBUG 13504 --- [nio-9700-exec-6] c.u.k.m.VoucherMapper.sqlBuilderInt      : ==> Parameters: 
2021-05-12 11:30:34.654 DEBUG 13504 --- [nio-9700-exec-7] c.u.k.mapper.VoucherMapper.selectList    : ==>  Preparing: SELECT code,gscode,kjnd,kjqj,zdrq,pzh,memo1,memo2,ztzb,pzlb,zdr,zy,kjkm,kmmc,bz,ybjfje,bbjfje,ybdfje,bbdfje,khfzhs,fwlxm,bmfzhs,xmfzhs,lydjname,lydj_dbname,lydj_id FROM uto_view_kb_020 WHERE kjnd = ? AND kjqj = ? AND code NOT IN (select isnull(vouchercode,'') from VoucherSummary) ORDER BY code DESC offset 50*0 rows fetch next 50 rows only; 
2021-05-12 11:30:34.656 DEBUG 13504 --- [nio-9700-exec-7] c.u.k.mapper.VoucherMapper.selectList    : ==> Parameters: 2020(String), 01(String)
2021-05-12 11:30:35.184 DEBUG 13504 --- [nio-9700-exec-6] c.u.k.m.VoucherMapper.sqlBuilderInt      : <==      Total: 1
2021-05-12 11:30:35.549 DEBUG 13504 --- [nio-9700-exec-7] c.u.k.mapper.VoucherMapper.selectList    : <==      Total: 0

以上是系统打印的日志
--------------------------------------------------------------------------------
### 2021-05-12 11:30:34.654 DEBUG 13504 --- [nio-9700-exec-7] c.u.k.mapper.VoucherMapper.selectList    : ==>  
 SELECT code,gscode,kjnd,kjqj,zdrq,pzh,memo1,memo2,ztzb,pzlb,zdr,zy,kjkm,kmmc,bz,ybjfje,bbjfje,ybdfje,bbdfje,khfzhs,fwlxm,bmfzhs,xmfzhs,lydjname,lydj_dbname,lydj_id FROM uto_view_kb_020 WHERE kjnd = ? AND kjqj = ? AND code NOT IN (select isnull(vouchercode,'') from VoucherSummary) ORDER BY code DESC offset 50*0 rows fetch next 50 rows only; 

以上为插件打印的

**Comment by PerccyKing** [comment]
这个数据库类型是什么呢？我将数据库类型配置为SQLserver能正常解析的呢

**Comment by tdoor** [comment]
就是SQLserver 配置我也改了

**Comment by PerccyKing** [comment]
你尝试一下吧日志复制到格式化窗口里面，进行格式化，看看能不能正常解析呢，我这边设置数据库类型为SQLserver 然后在格式化窗口中解析式没有问题的

**Comment by tdoor** [comment]
2021-05-12 16:13:38.313  INFO 17920 --- [nio-9700-exec-5] com.zaxxer.hikari.HikariDataSource       : SpringBootDemoHikariCP - Starting...
2021-05-12 16:13:38.754  INFO 17920 --- [nio-9700-exec-5] com.zaxxer.hikari.HikariDataSource       : SpringBootDemoHikariCP - Start completed.
2021-05-12 16:13:38.759 DEBUG 17920 --- [nio-9700-exec-2] c.u.k.mapper.VoucherMapper.selectList    : ==>  Preparing: SELECT code,gscode,kjnd,kjqj,zdrq,pzh,memo1,memo2,ztzb,pzlb,zdr,zy,kjkm,kmmc,bz,ybjfje,bbjfje,ybdfje,bbdfje,khfzhs,fwlxm,bmfzhs,xmfzhs,lydjname,lydj_dbname,lydj_id FROM uto_view_kb_020 WHERE kjnd = ? AND kjqj = ? AND code NOT IN (select isnull(vouchercode,'') from VoucherSummary) ORDER BY code DESC offset 50*0 rows fetch next 50 rows only; 
2021-05-12 16:13:38.776 DEBUG 17920 --- [nio-9700-exec-2] c.u.k.mapper.VoucherMapper.selectList    : ==> Parameters: 2020(String), 10(String)
2021-05-12 16:13:38.824 DEBUG 17920 --- [nio-9700-exec-5] c.u.k.m.VoucherMapper.sqlBuilderInt      : ==>  Preparing: select count(*) from uto_view_kb_020 where code not in (select isnull(vouchercode,'') from VoucherSummary) and kjnd = 2020 and kjqj = 10 
2021-05-12 16:13:38.825 DEBUG 17920 --- [nio-9700-exec-5] c.u.k.m.VoucherMapper.sqlBuilderInt      : ==> Parameters: 
2021-05-12 16:13:39.428 DEBUG 17920 --- [nio-9700-exec-2] c.u.k.mapper.VoucherMapper.selectList    : <==      Total: 0
2021-05-12 16:13:39.473 DEBUG 17920 --- [nio-9700-exec-5] c.u.k.m.VoucherMapper.sqlBuilderInt      : <==      Total: 1

以上是系统打印的日志
------------------------------------------------------------------------
[https://ae01.alicdn.com/kf/U16c626baa2d0455bbfa2cac50eeaddb8p.jpg](url)

**Comment by PerccyKing** [comment]
![image](https://user-images.githubusercontent.com/59950759/117943262-8378ac00-b33e-11eb-916b-839e43e6c00b.png)
你看看这个地方有没有异常呢

**Comment by tdoor** [comment]
`java.lang.StringIndexOutOfBoundsException: String index out of range: -6
	at java.base/java.lang.String.substring(String.java:1841)
	at cn.com.pism.batslog.util.SqlFormatUtils.format(SqlFormatUtils.java:67)
	at cn.com.pism.batslog.ui.FormatWindow.format(FormatWindow.java:104)
	at cn.com.pism.batslog.ui.FormatWindow.lambda$initFormAction$0(FormatWindow.java:80)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6650)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:730)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:708)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1644)
	at cn.com.pism.batslog.ui.FormatWindow.<init>(FormatWindow.java:76)
	at cn.com.pism.batslog.ui.FormatWindow.show(FormatWindow.java:162)
	at cn.com.pism.batslog.action.OpenFormatWindowAction.actionPerformed(OpenFormatWindowAction.java:25)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:274)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:184)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:442)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

![0512162859](https://user-images.githubusercontent.com/54176978/117943902-2fba9280-b33f-11eb-8ded-5fc3dc0710b0.png)

**Comment by PerccyKing** [comment]
在你的项目文件夹下面会有一个 .idea 的文件夹，这个文件夹下面有个BatsLog.xml 的文件，麻烦把文件的内容发给我看看呢

**Comment by tdoor** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="BatsLogSettingState">
    <option name="dbType" value="SqlServer" />
    <option name="keyWordDefCol" value="{&quot;r&quot;:31,&quot;g&quot;:204,&quot;b&quot;:169,&quot;alpha&quot;:255}" />
  </component>
</project>`

**Comment by PerccyKing** [comment]
这个我这边依然没能复现，麻烦等我下个版本发布，然后再试一下，我会加入一个调试模式进去，方便问题定位

**Comment by PerccyKing** [comment]
你好，麻烦你尝试一下这个包，看看还有没有你说的情况呢，期待你的使用反馈，谢谢 [21.05.24.2037](https://github.com/PerccyKing/batslog/releases/download/21.05.24.2037/batslog-21.05.24.2037-SN.zip)
使用方法:(卸载之前版本的插件-可选)下载batslog-21.05.24.2037-SN.zip，直接拖入idea，然后重启idea

**Comment by tdoor** [comment]
首先感谢作者热心更新维护,问题基本已经定位
-------------------------------------------------------
`        int pageNum = (data.getInt("Page") - 1)*50;
        QueryWrapper<Voucher> wrapper = new QueryWrapper<>();
        wrapper.eq("kjnd", data.getStr("NF"))
                .eq("kjqj", data.getStr("YF"))
                .orderByDesc("code")
                .last( "offset "+ pageNum +" rows fetch next 50 rows only;");`

这是最终优化后的.last()函数,这种写法可以正常解析出参数
但是pageNum这个计算参数无法直接写入SQL需要第一行计算出后直接填入,也就是说我之前的写法
`.last("offset 50*" + pageNum + " rows fetch next 50 rows only;");`
是无法被解析的.
起初我以为是.last()中拼接参数导致无法读取的,后来发现是`50*pageNum`的问题

**Comment by PerccyKing** [comment]
你好， [21.05.27.2253](https://github.com/PerccyKing/batslog/releases/tag/21.05.27.2253) 已发布，你可以等待jetbrain应用商店上架后升级使用，也可以直接下载，抢先使用（如果你正在使用<h3 color='res'>21.05.24.2037</h3>版本，请卸载该版本，重新安装），感谢你的支持 [点击下载最新版本](https://github.com/PerccyKing/batslog/releases/download/21.05.27.2253/batslog-21.05.27.2253-RE.zip)
