### ISSUE TITLE
经常报StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by heyaping388** [PerccyKing/batslog#12]
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 5
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at cn.com.pism.batslog.util.SqlFormatUtils.format(SqlFormatUtils.java:79)
	at cn.com.pism.batslog.util.SqlFormatUtils.format(SqlFormatUtils.java:40)
	at cn.com.pism.batslog.util.SqlFormatUtils.format(SqlFormatUtils.java:36)
	at cn.com.pism.batslog.points.BatsLogConsoleFolding.shouldFoldLine(BatsLogConsoleFolding.java:52)
	at com.intellij.execution.impl.ConsoleViewImpl.foldingForLine(ConsoleViewImpl.java:1178)
	at com.intellij.execution.impl.ConsoleViewImpl.lambda$updateFoldings$14(ConsoleViewImpl.java:1118)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:211)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:186)
	at com.intellij.openapi.editor.FoldingModel.runBatchFoldingOperation(FoldingModel.java:96)
	at com.intellij.execution.impl.ConsoleViewImpl.updateFoldings(ConsoleViewImpl.java:1081)
	at com.intellij.execution.impl.ConsoleViewImpl.highlightHyperlinksAndFoldings(ConsoleViewImpl.java:1027)
	at com.intellij.execution.impl.ConsoleViewImpl.flushDeferredText(ConsoleViewImpl.java:744)
	at com.intellij.execution.impl.ConsoleViewImpl$FlushRunnable.doRun(ConsoleViewImpl.java:1659)
	at com.intellij.execution.impl.ConsoleViewImpl$FlushRunnable.run(ConsoleViewImpl.java:1655)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:203)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by PerccyKing** [comment]
你好，这个错误会持续优化的，如果有日志解析不出来，可以把日志的敏感信息处理一下，然后发出来我看一下

**Comment by PerccyKing** [comment]
你好，麻烦你尝试一下这个包，看看还有没有你说的情况呢，期待你的使用反馈，谢谢 [21.05.24.2037](https://github.com/PerccyKing/batslog/releases/download/21.05.24.2037/batslog-21.05.24.2037-SN.zip)
使用方法:下载batslog-21.05.24.2037-SN.zip，直接拖入idea，然后重启idea

**Comment by PerccyKing** [comment]
你好，该错误已经在 [21.05.27.2253](https://github.com/PerccyKing/batslog/releases/tag/21.05.27.2253) 发布，你可以等待jetbrain应用商店上架后升级使用，也可以直接下载，抢先使用（如果你正在使用<h3 color='res'>21.05.24.2037</h3>版本，请卸载该版本，重新安装），感谢你的支持 [点击下载最新版本](https://github.com/PerccyKing/batslog/releases/download/21.05.27.2253/batslog-21.05.27.2253-RE.zip)
