### ISSUE TITLE
关于启动时插件自动更新的建议

### ISSUE THREAD

**Issue by Nasller** [PerccyKing/batslog#26]
是否可以使用异步的方式去实现插件的更新提示呢，在有些网络不是很通畅的情况下，启动容易卡死，HttpUtil 也应该设置一下timeout
![QQ截图20220113164843](https://user-images.githubusercontent.com/26132153/149296971-2ff06141-2124-4555-9a73-8a1f66ece999.png)

freezeLog:

"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at java.base@11.0.13/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.13/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base@11.0.13/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1426)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1336)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base@11.0.13/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
	at java.base@11.0.13/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base@11.0.13/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at cn.hutool.http.HttpConnection.connect(HttpConnection.java:375)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1193)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1076)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:967)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:943)
	at cn.hutool.http.HttpUtil.get(HttpUtil.java:145)
	at cn.hutool.http.HttpUtil.get(HttpUtil.java:133)
	at cn.com.pism.batslog.action.StartUpAction.versionCheck(StartUpAction.java:62)
	at cn.com.pism.batslog.action.StartUpAction.runActivity(StartUpAction.java:55)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:312)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:293)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:288)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$2.run(StartupManagerImpl.kt:256)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:387)
	at com.intellij.openapi.project.DumbServiceImpl$$Lambda$5777/0x00000008028c1040.run(Unknown Source)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$370/0x0000000800584440.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop@11.0.13/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.13/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop@11.0.13/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.13/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.13/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.13/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.13/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.ide.IdeEventQueue$$Lambda$695/0x0000000800941040.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.ide.IdeEventQueue$$Lambda$694/0x0000000800940040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by PerccyKing** [comment]
收到，晚上就发版

**Comment by PerccyKing** [comment]
> 是否可以使用异步的方式去实现插件的更新提示呢，在有些网络不是很通畅的情况下，启动容易卡死，HttpUtil 也应该设置一下timeout
> ![QQ截图20220113164843](https://user-images.githubusercontent.com/26132153/149296971-2ff06141-2124-4555-9a73-8a1f66ece999.png)
> 
> freezeLog:
> 
> "AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
>      java.lang.Thread.State: RUNNABLE
>  (in native)
> 	at java.base@11.0.13/java.net.SocketInputStream.socketRead0(Native Method)
> 	at java.base@11.0.13/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
> 	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:168)
> 	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:140)
> 	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
> 	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
> 	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
> 	at java.base@11.0.13/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
> 	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1426)
> 	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1336)
> 	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
> 	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
> 	at java.base@11.0.13/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
> 	at java.base@11.0.13/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
> 	at java.base@11.0.13/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
> 	at cn.hutool.http.HttpConnection.connect(HttpConnection.java:375)
> 	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1193)
> 	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1076)
> 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:967)
> 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:943)
> 	at cn.hutool.http.HttpUtil.get(HttpUtil.java:145)
> 	at cn.hutool.http.HttpUtil.get(HttpUtil.java:133)
> 	at cn.com.pism.batslog.action.StartUpAction.versionCheck(StartUpAction.java:62)
> 	at cn.com.pism.batslog.action.StartUpAction.runActivity(StartUpAction.java:55)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:312)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:293)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:288)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$2.run(StartupManagerImpl.kt:256)
> 	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:395)
> 	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:387)
> 	at com.intellij.openapi.project.DumbServiceImpl$$Lambda$5777/0x00000008028c1040.run(Unknown Source)
> 	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
> 	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$370/0x0000000800584440.run(Unknown Source)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
> 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
> 	at java.desktop@11.0.13/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop@11.0.13/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
> 	at java.desktop@11.0.13/java.awt.EventQueue$4.run(EventQueue.java:727)
> 	at java.desktop@11.0.13/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.base@11.0.13/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base@11.0.13/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop@11.0.13/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
> 	at com.intellij.ide.IdeEventQueue$$Lambda$695/0x0000000800941040.compute(Unknown Source)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
> 	at com.intellij.ide.IdeEventQueue$$Lambda$694/0x0000000800940040.run(Unknown Source)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
> 	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop@11.0.13/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

收到，晚上就发版
