### ISSUE TITLE
插件日志错误 SQL监听失败

### ISSUE THREAD

**Issue by fish-kings** [PerccyKing/batslog#44]
![image](https://github.com/PerccyKing/batslog/assets/67667211/52b164a9-3d69-41a3-acec-dc0647dc0cb2)
![image](https://github.com/PerccyKing/batslog/assets/67667211/aa820486-388b-48b8-a4a9-4e67e0617ffe)
 这个问题在IDEA 2022 的版本就存在很久 好像上次更新了插件使用了一段时间没有 现在在2023.1这个版本又出现 希望能修复一下

**Comment by fish-kings** [comment]
具体错误位置在 是不是遇见空行导致的问题       
at cn.com.pism.batslog.util.SqlFormatUtil.notEnabledMultiSqlPrefix(SqlFormatUtil.java:235)
	at cn.com.pism.batslog.util.SqlFormatUtil.format(SqlFormatUtil.java:116)
	at cn.com.pism.batslog.util.SqlFormatUtil.format(SqlFormatUtil.java:80)
	at cn.com.pism.batslog.util.BatsLogUtil.copySqlToClipboard(BatsLogUtil.java:31)
	at cn.com.pism.batslog.action.CopySqlAction.actionPerformed(CopySqlAction.java:42)

**Comment by fish-kings** [comment]
notEnabledMultiSqlPrefix这个是在手动处理日志的时候出现的问题 但是SQL自动监听失败请您排查一下

**Comment by PerccyKing** [comment]
好的，最近有点忙，我后面排查一下😂
